services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=rabbitmq_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - 5433:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgres/data
    networks:
      - postgres-network

  rabbit-mq:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672

networks:
  postgres-network:
    driver: bridge